sudo: enabled
services:
  - docker
language: python
dist: trusty
before_install:
  - docker run postgres:9.6.3-alpine -d
  - docker build -t uditnarayan/django_postgresql_travis_demo .
  - docker run -d -p 127.0.0.1:8000:8000 uditnarayan/django_postgresql_travis_demo
  - docker ps -a
  - docker run uditnarayan/django_postgresql_travis_demo /bin/sh -c "cd /app; python manage.py test;"
script:
  - python manage.py test
